"""04_add_email_to_user

Revision ID: 556ff57f05d7
Revises: f7751ffad0be
Create Date: 2025-01-04 22:38:38.248840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "556ff57f05d7"
down_revision: Union[str, None] = "f7751ffad0be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("email", sa.String(length=255), nullable=True),
    )
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
