# Generated by Django 5.1.1 on 2024-10-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='certificate',
            field=models.CharField(blank=True, null=True, max_length=512, verbose_name='certificate'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='filmworks/', verbose_name='file'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.TextField(blank=True, choices=[('male', 'male'), ('female', 'female')], null=True, verbose_name='gender'),
        ),
    ]
